#! /usr/bin/env ruby

require 'builder'
require 'fileutils'
require 'yaml'

def dir_blacklist
  ["css", "sass", "script", "js"]
end

def useless?(f)
  f.start_with?("_") ||
    f.start_with?(".") ||
    !File.directory?(f) ||
    dir_blacklist.include?(f)
end

def get_gif_dirs
  Dir.foreach(".").map { |f| f unless useless?(f) }.compact
end

def liquid_info_for_file(dir, filename)
  path = File.join(filename)
  {
    "path"          => "/public/images/memes/"+path,
    "modified_time" => File.mtime(path).to_i,
    "extname"       => File.extname(path)
  }
end

list = Builder::XmlMarkup.new(
  target: File.open("../../../_includes/memes-index.html", 'w'),
  indent: 0,
  margin: 0
)

dirs  = get_gif_dirs
files = []

list.ul do |builder|
  dirs.each do |dir|
    builder.li do |dir_element|
      dir_element.text!(dir)
      dir_element.ul do |ul|
        Dir.glob("#{dir}/*.*") do |gif|
          files << liquid_info_for_file(dir, gif)
          ul.li do |li|
            li.a(
              File.basename(gif),
              "href"  => "/public/images/memes/"+gif,
              "title" => "/public/images/memes/"+gif,
              "class" => "gif"
            )
          end
        end
      end
    end
  end
end

FileUtils.mkdir_p("../../../_data") unless File.directory?("_data")
File.open("../../../_data/memes_static_files.yml", 'w') { |f| f.write(YAML.dump(files)) }
